### ISSUE TITLE
[Bug]: Fix nested reverts

### ISSUE THREAD

**Issue by saucepoint** [Uniswap/v4-periphery#102]
### Describe the bug

In Quoter, there's a nested revert that's not bubbling up correctly

### Expected Behavior

The earliest revert should bubble up

### Additional context

https://github.com/Uniswap/v4-periphery/pull/100#discussion_r1526634096

**Comment by nishim3** [comment]
![image](https://github.com/Uniswap/v4-periphery/assets/115455855/56c7bcb5-c02a-4d6a-962d-be03c196b1ac)
The sender and the manager have the same address, so the ```revert InvalidLockAcquiredSender();``` line is not reached through the tests...
