### ISSUE TITLE
[Bug]: In the example for hooks, not using safe transfer from 

### ISSUE THREAD

**Issue by mr-uniswap** [Uniswap/v4-periphery#107]
### Describe the bug

In https://github.com/Uniswap/v4-periphery/blob/6616b12db25257ffb3c562f131612ebb2fd89082/contracts/hooks/examples/LimitOrder.sol#L269-L276 we're not using safe transferfrom. There is a todo, but it is not implemented. 

### Expected Behavior

Use safe transfer from in the example.

**Comment by saucepoint** [comment]
closing this issue for now, since example hooks do not live in the main branch anymore.

i've added a revisit tag as a reminder

**Comment by guotie** [comment]
Where can I find the examples?
