### ISSUE TITLE
[Bug]: Fix BaseHook with latest v4-core update

### ISSUE THREAD

**Issue by tomwade** [Uniswap/v4-periphery#111]
### Describe the bug

After [this PR](https://github.com/Uniswap/v4-core/pull/482) the `BaseHook.sol` code no longer matches the `IHooks.sol` interface.

### Expected Behavior

The params and return data should be updated in `BaseHook.sol`

**Comment by tomwade** [comment]
Sorry, I wasn't able to create this as a PR, but the changes to make this fix are minimal:
- `beforeAddLiquidity` adds `BalanceDelta` param and `BalanceDelta` return
- `afterAddLiquidity` adds `BalanceDelta` return
- `beforeSwap` adds `int128` return
- `afterSwap` adds `int128` return

I have confirmed that this works on a local branch

**Comment by hensha256** [comment]
thank you! yes we periodically update the v4-core commit that is used in periphery! hopefully we can get it updated soon but will take a bit of work with the 2 bigger changes that went in today!
