### ISSUE TITLE
[posm]: Add Permit functionality to ERC721

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/v4-periphery#167]
### Component

Position Manager

### Describe the suggested feature and problem it solves.

Permit should: 
- [x] Use unordered nonces
- [x] Not be payable (in V3 it is payable)
- [ ] Use relevant libraries and base contracts (ie a PermitHash [library](https://github.com/Uniswap/v4-periphery/pull/153#discussion_r1681402782)) and a EIP1271 base contract that caches the domain separator. (see comments [here](https://github.com/Uniswap/v4-periphery/pull/153#discussion_r1681374875).
- [x] Constants above functions
- [x] Test: Ensure PERMIT_TYPEHASH is equal to expected hash
- [x] Use custom errors
- [x] replace magic constant with IERC1271.isValidSignature.selector
- [x] [this](https://github.com/Uniswap/v4-periphery/pull/141#discussion_r1684211300) comment

Ensure that all comments related to permit from [this PR](https://github.com/Uniswap/v4-periphery/pull/153) and [this PR](https://github.com/Uniswap/v4-periphery/pull/141) are resolved in the final feature PR.

**Comment by saucepoint** [comment]
note to self: ensure permit is payable with a test for permit & increase with native tokens `multicall{value: x}(permit, increase)`

https://github.com/Uniswap/v4-periphery/pull/189#pullrequestreview-2196904827
