### ISSUE TITLE
LimitOrderHook improvements

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/v4-periphery#2]
# Infra improvements

- way more tests

# Contract improvements

- consider simplifying the epoch/key data structures (https://github.com/Uniswap/core-next/pull/93#discussion_r888166349)
- consider renaming epochs -> orders (https://github.com/Uniswap/core-next/pull/93#discussion_r889726019)
- consider a bitmap to track initialized ticks (https://github.com/Uniswap/core-next/pull/93#discussion_r889730737)
- consider a single call to fill per swap (https://github.com/Uniswap/core-next/pull/93#discussion_r889739044)

# UX-level changes

- consider taking `amountIn` instead of `liquidity` (https://github.com/Uniswap/core-next/pull/93#discussion_r888143083)
- consider issuing erc721/erc1155/erc20 representations of limit orders

**Comment by saucepoint** [comment]
closing this issue for now, since example hooks do not live in the main branch anymore.

i've added a revisit tag as a reminder
