### ISSUE TITLE
ERC721Permit: PermitForAll

### ISSUE THREAD

**Issue by saucepoint** [Uniswap/v4-periphery#227]
### Component

Position Manager

### Describe the suggested feature and problem it solves.

Explore supporting a signature-based permit to set operators

i.e. if `permit` is to `approve` then `permitForAll` is to `setApprovalForAll`

**Comment by hieronx** [comment]
@saucepoint maybe worth trying to adapt ERC-7741 to work for this use case: https://eips.ethereum.org/EIPS/eip-7741 We designed this to work for the operator model that exists in both ERC-6909 and ERC-7540. Seems like it could also fit for this purpose. Would be happy to collaborate on adapting the ERC accordingly, to try to make this standardized.
