### ISSUE TITLE
[Bug]: URL for `v4-core` in `.gitmodules` leads to `Permission denied` error

### ISSUE THREAD

**Issue by apoorvlathey** [Uniswap/v4-periphery#25]
### Describe the bug

Executing `forge install` fails for `lib/v4-core` with the following:
```
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Uniswap/v4-core.git' into submodule path './v4-periphery/lib/v4-core' failed
Failed to clone 'lib/v4-core'. Retry scheduled
Cloning into './v4-periphery/lib/v4-core'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

### Expected Behavior

Replace url in `.gitmodules` from `git@github.com:Uniswap/v4-core.git` to `https://github.com/Uniswap/v4-core`

**Comment by sm-stack** [comment]
I think the problem does not come from the `.gitmodules`, but it comes from the permission of Linux itself. I got no problem when  I tried to install with the root user.

**Comment by BedrosovaYulia** [comment]
have the same issue

**Comment by usgeeus** [comment]
have the same issue

**Comment by skywalker2017** [comment]
regenerate the public key can solve the problem

**Comment by saucepoint** [comment]
Closed with https://github.com/Uniswap/v4-periphery/pull/97
