### ISSUE TITLE
[Bug]: Instead of using bytes32 poolId we could use PoolId id by creating a custom type

### ISSUE THREAD

**Issue by stephenatgithub** [Uniswap/v4-periphery#28]
### Describe the bug

Instead of using bytes32 poolId we could use PoolId id by creating a custom type

It is already applied in v4-core. [#223](https://github.com/Uniswap/v4-core/pull/223)

There is compilation error so need to apply the same in v4-periphery.

### Expected Behavior

No more compile error

**Comment by saucepoint** [comment]
Closed in #29, feel free to reopen if thats not the case
