### ISSUE TITLE
TwammHook: Finish Migrating tests

### ISSUE THREAD

**Issue by ewilz** [Uniswap/v4-periphery#30]
### Component

Pool Interaction, Hooks

### Describe the suggested feature and problem it solves.

Tests to migrate in these commits:
https://github.com/Uniswap/v4-periphery/pull/20/commits/ebc63416504c6fb3239751f2e5b872ab624735dc
https://github.com/Uniswap/v4-periphery/pull/20/commits/384629688e981a22cd2b561043c534dc729eed59

+ fuzz tests

**Comment by saucepoint** [comment]
closing this issue for now, since example hooks do not live in the main branch anymore.

i've added a revisit tag as a reminder

**Comment by ewilz** [comment]
More tests pertaining to "claim tokens" would be good.
