### ISSUE TITLE
TwammHook: Address math imprecision on single sell pools

### ISSUE THREAD

**Issue by ewilz** [Uniswap/v4-periphery#31]
### Component

Pool Interaction, Hooks

### Describe the suggested feature and problem it solves.

Because single-side sell TWAMM pools math is calculated slightly differently, math imprecision leads to selling a few wei more than what's available. Must address imprecision.

https://github.com/Uniswap/v4-periphery/blob/main/test/TWAMM.t.sol#L132

**Comment by xben12** [comment]
Hey ewilz, one math imprecision in single sell pool is the amount to token to swap:

1) the current code ignore this parameter by using type(int256).max
poolManager.lock(abi.encode(key, IPoolManager.SwapParams(zeroForOne, type(int256).max, sqrtPriceLimitX96)));

2) the amountIn backout from sqrtPriceLimitX96 can be larger than the total amount to sell on the single side. this will lead the code to revert. we can cap this number by calculate the exact amount to be swapped. 

I have developed this code and need a right to new branch for open PR. 

<img width="827" alt="Screenshot 2023-10-14 at 2 56 56 PM" src="https://github.com/Uniswap/v4-periphery/assets/68003841/7d0f2580-269f-4993-902b-2afcaa5589ce">

**Comment by saucepoint** [comment]
closing this issue for now, since example hooks do not live in the main branch anymore.

i've added a revisit tag as a reminder

**Comment by ewilz** [comment]
fixed in slightly different manner

**Comment by ewilz** [comment]
Sorry, fixed ben's suggestion slightly differently. Still might be worth looking into the math imprecision because it is off by more than just some wei.
