### ISSUE TITLE
[Bug]: Argument Mismatch in afterAddLiquidity and afterRemoveLiquidity Functions with v4-core

### ISSUE THREAD

**Issue by DamirS09** [Uniswap/v4-periphery#328]
### Describe the bug

There is a discrepancy in the function signatures of **afterAddLiquidity** and **afterRemoveLiquidity** between the **v4-periphery** and **v4-core** repositories.

### Expected Behavior

The function signatures in v4-periphery should be updated to match those in v4-core, including the BalanceDelta feesAccrued parameter. This ensures consistency and compatibility between the core and periphery layers.

### To Reproduce

[v4-core: afterAddLiquidity](https://github.com/Uniswap/v4-core/blob/main/src/interfaces/IHooks.sol#L63)
[v4-periphery: afterAddLiquidity](https://github.com/Uniswap/v4-periphery/blob/main/src/base/hooks/BaseHook.sol#L83)
[v4-core: afterRemoveLiquidity](https://github.com/Uniswap/v4-core/blob/main/src/interfaces/IHooks.sol#L94)
[v4-periphery: afterRemoveLiquidity](https://github.com/Uniswap/v4-periphery/blob/main/src/base/hooks/BaseHook.sol#L93)

### Additional context

In v4-core, both functions take an additional parameter: BalanceDelta feesAccrued.
The v4-periphery implementation lacks this parameter, which leads to incompatibility issues.

This discrepancy is present in the [v4-periphery](https://github.com/Uniswap/v4-periphery/blob/main/src/base/hooks/BaseHook.sol) repository, specifically in the file: src/base/hooks/BaseHook.sol.

**Comment by hensha256** [comment]
Hi! Yes we have to manually update the core commit that is used in periphery. We changed core a few days ago so need to manually update in periphery. Will aim to get that in today or tomorrow for you :)

**Comment by hensha256** [comment]
The update to core was created here https://github.com/Uniswap/v4-core/commit/3407bce4b39869fe41ad5ec724b2df308c34900f

**Comment by DamirS09** [comment]
> Hi! Yes we have to manually update the core commit that is used in periphery. We changed core a few days ago so need to manually update in periphery. Will aim to get that in today or tomorrow for you :)

Hi! Thank you for the quick response!

I appreciate the update and will look forward to the changes being implemented in the periphery repository. 
Thanks again! 😊

**Comment by saucepoint** [comment]
should be fixed now with:

https://github.com/Uniswap/v4-periphery/pull/337
