### ISSUE TITLE
License changes to encourage hook developments 

### ISSUE THREAD

**Issue by 0xCheetah** [Uniswap/v4-periphery#351]
As it was discussed in the Uniswap HackerHouse event, it will be great if all multicall & permit scripts become MIT licensed. It will also encourage new directions for hook creations.

**A. Multicall:** One benefit is that the community will be enabled to build hooks that incorporate multicall in them with any license. This is particularly useful for hooks that interact directly with v4 core, as opposed to the periphery, as they may need to trigger a sequence of calls to the core. For example, an aggregator contract which is also a hook.

- v4-periphery/src/base/Multicall_v4.sol (now GPL)
- v4-periphery/src/interfaces/IMulticall_v4.sol (now UNLICENSED)

**B. Permit2:** Similar to the previous argument, Permit2Forwarder can be readily used by any contract that interacts directly with v4 core. Making Permit2Forwarder MIT encourages permit2 adoption.

- v4-periphery/src/base/Permit2Forwarder.sol (now GPL)

**C. ERC721Permit:** Similar to the previous argument, it encourages new directions for hook creations, when hooks issue NFTs.

- v4-periphery/src/base/ERC721Permit_v4.sol (now GPL)
- v4-periphery/src/interfaces/IERC721Permit_v4.sol (now GPL)
- v4-periphery/src/base/UnorderedNonce.sol (now GPL)
- v4-periphery/src/libraries/ERC721PermitHash.sol (now GPL)

@hensha256 @snreynolds @saucepoint

**Comment by snreynolds** [comment]
Hi there we introduced some updates to the license in this PR https://github.com/Uniswap/v4-periphery/pull/400
