### ISSUE TITLE
Loss vs Rebalancing (LVR) Hook

### ISSUE THREAD

**Issue by ewilz** [Uniswap/v4-periphery#37]
### Component

Pool Interaction, Hooks

### Describe the suggested feature and problem it solves.

To consult with research / @aadams for a more concrete spec.

the basic intuition is that we assume the existence of a sophisticated builder, they declare what the price will be at the end of the block (and provide a deposit to guarantee that end price), and they are taxed some percentage of the implied arbitrage profit they can get from that.

eth research post about LVR:
https://ethresear.ch/t/lvr-minimization-in-uniswap-v4/15900

**Comment by saucepoint** [comment]
closing this issue for now, since example hooks do not live in the main branch anymore.

i've added a revisit tag as a reminder
