### ISSUE TITLE
Routing Contracts 

### ISSUE THREAD

**Issue by ewilz** [Uniswap/v4-periphery#38]
### Component

Pool Interaction, Swaps, Pool Interaction, Settle/Take/Mint

### Describe the suggested feature and problem it solves.

Develop a swap router. With the introduction of things like Universal Router and multi-version routers (i.e. SwapRouter02)
Could be nice to include extensible abstract contracts (or libraries?) in this repo to be used in external contracts. But at least have a sound router example code in here.

**Comment by saucepoint** [comment]
https://github.com/Uniswap/v4-periphery/pull/58
