### ISSUE TITLE
liquidity incentives support hook

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/v4-periphery#4]
need a hook to have feature parity with v3 in terms of how liquidity incentives are disbursed

in v3 we had seconds per liquidity tracked globally via the oracle and per tick via secondsPerLiquidityOutsideX128

in v4 we removed it, so it needs to be supported via a hook

the hook can simply track this variable for any tick range

it can also surface an `epoch` variable so people can know whether the two snapshots they took were within the same epoch, i.e. at least 1 liquidity existed on both ticks for the duration of the snapshot

**Comment by saucepoint** [comment]
closing this issue for now, since example hooks do not live in the main branch anymore.

i've added a revisit tag as a reminder

---

Also the subscribers/notifiers logic in PositionManager were designed to facilitate liquidity incentives, so worth exploring that as well
