### ISSUE TITLE
Dynamic Fee on Arbitrage Hook

### ISSUE THREAD

**Issue by ewilz** [Uniswap/v4-periphery#40]
### Component

Pool Interaction, Hooks

### Describe the suggested feature and problem it solves.

Create a hook that can set a dynamic fee at the top of the block depending on the direction of price movement over the previous block(s). If the price of tokenA has risen in the past block(s), fees to buy tokenA should rise, and fees to buy tokenB should fall by the same rate. This acts as a mechanism to share arbitrage profits with LPs.

Discriminates more towards arbitrageurs, who are more likely to be moving in the direction of real price movement relative to the average swapper. 

h/t https://twitter.com/0x94305/status/1674857993740111872

**Comment by saucepoint** [comment]
closing this issue for now, since example hooks do not live in the main branch anymore.

i've added a revisit tag as a reminder
