### ISSUE TITLE
Sync compiler version with v4-core

### ISSUE THREAD

**Issue by starit** [Uniswap/v4-periphery#42]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

Right now, the solc version of [v4-periphery](https://github.com/Uniswap/v4-periphery) is using is `^0.8.19`, however, the solc version in `v4-core` is `^0.8.20`

It caused some inconvenient when we add both repos to the lib of a new repo (by `forge install`) and import those `.sol` files from both repos, especially, the interfaces files

This is going to be helpful for improving the developer experience.

### Describe the desired implementation.

Change all the compiler versions in v4-periphery to `^0.8.20`

### Additional context.

We need also to ensure those changes are not going to have a bad impact on the v4-periphery repo, due to it being a small change, I believe it's not going to be a big problem.

**Comment by saucepoint** [comment]
closing as we've pinned `solc_version = "0.8.24"` and `evm_version = "cancun"` in foundry.toml for both v4-core and v4-peirphery
