### ISSUE TITLE
[Bug]: Shadowed storage vars in TWAMM.sol

### ISSUE THREAD

**Issue by kadenzipfel** [Uniswap/v4-periphery#53]
### Describe the bug

Throughout the TWAMM.sol contract, the storage var `poolManager` is often shadowed by a function parameter by the same name

### Expected Behavior

The function parameter should be renamed, e.g. as `_poolManager`, to avoid shadowing the storage var

**Comment by saucepoint** [comment]
closing this issue for now, since example hooks do not live in the main branch anymore.

i've added a revisit tag as a reminder
