### ISSUE TITLE
[Bug]: Tests failing due to currencies out of order

### ISSUE THREAD

**Issue by kadenzipfel** [Uniswap/v4-periphery#54]
### Describe the bug

When pools are initialized in the test cases, the tests are failing due to the currencies being set out of order. 

```solidity
// If token0 > token1, initialization fails
token0 = new TestERC20(2**128);
token1 = new TestERC20(2**128);
```

### Expected Behavior

The tokens provided should be checked to ensure they're in the correct order, and if not, reorder them.

**Comment by ewilz** [comment]
I think you're writing about periphery not being caught up with core.....planning to merge this tomorrow. https://github.com/Uniswap/v4-periphery/pull/50

**Comment by kadenzipfel** [comment]
> I think you're writing about periphery not being caught up with core.....planning to merge this tomorrow. #50

Ahh yes looks like you already covered this, thanks for pointing that out
