### ISSUE TITLE
Add param names to BaseHook

### ISSUE THREAD

**Issue by naddison36** [Uniswap/v4-periphery#56]
### Component

Pool Interaction, Hooks

### Describe the suggested feature and problem it solves.

Please add the parameter names to the hook functions in the `BaseHook` contract.

Yes, the Solidity compiler will spit out warnings that these parameters are not used, but the purpose of `BaseHook` is to allow developers to extend it. Knowing what the parameters are without having to look at the `IHook` interface is very useful.

### Describe the desired implementation.

Instead of
```Solidity
    function afterSwap(address, PoolKey calldata, IPoolManager.SwapParams calldata, BalanceDelta)
        external
        virtual
        returns (bytes4)
    {
        revert HookNotImplemented();
    }
```

Add the parameter names
```Solidity
    function afterSwap(
        address sender,
        PoolKey calldata key,
        IPoolManager.SwapParams calldata params,
        BalanceDelta delta)
        external
        virtual
        returns (bytes4 selector)
    {
        revert HookNotImplemented();
    }
```

### Describe alternatives.

N/A

### Additional context.

Contract and tx visualisation tools like sol2uml and tx2uml can also use the parameter names

**Comment by naddison36** [comment]
Here's some example tx2uml call diagrams using Uniswap v4 hooks with parameter names https://github.com/naddison36/uniswap-v4-hooks/tree/main/docs#modify-liquidity

**Comment by saucepoint** [comment]
hey sorry for the slow response

the solidity compiler will throw warnings when variables are unused, so going to close this issue for now
