### ISSUE TITLE
Use deployCodeTo in hook tests

### ISSUE THREAD

**Issue by ferencdg** [Uniswap/v4-periphery#69]
### Component

General design optimization (improving efficiency, cleanliness, or developer experience)

### Describe the suggested feature and problem it solves.

You could use the deployCodeTo function in Hook tests from the Foundry standard library to deploy code to a specific address. The current way of creating a subclass looks a bit messy.

**Comment by saucepoint** [comment]
agreed we should move to deployCodeTo

given that we removed the hook examples from the main branch, this issue may not longer be relevant

reference PR #122
