### ISSUE TITLE
[Bug]: FullRange missing access controls (security bug) 

### ISSUE THREAD

**Issue by ferencdg** [Uniswap/v4-periphery#71]
### Describe the bug

beforeInitialize should check if it is called by the PoolManager and revert if it isn't

In the current version anyone can override the liquidityToken in the poolInfo

### Expected Behavior

only PoolManager should be able to call it

**Comment by saucepoint** [comment]
Hi! thanks for flagging -- going to close this issue because:

hook examples no longer live in the main branch

custom accounting will allow for a more v2-style curve with v2 interfaces. reference implementation https://github.com/hensha256/v2-on-v4
