### ISSUE TITLE
Change Deployers.createPool from private to public

### ISSUE THREAD

**Issue by ferencdg** [Uniswap/v4-periphery#72]
please make this function public:

function createPool(
        PoolManager manager,
        IHooks hooks,
        uint24 fee,
        uint160 sqrtPriceX96,
        bytes memory initData
    ) private returns (PoolKey memory key, PoolId id) 

The general flow of creating hooks in Tests is:

1. create the PoolManager with Deployers.createPoolManager()
2. create the Hook and pass in the poolManager
3. create the pool with Deployers.createPool

**Comment by hensha256** [comment]
We're doing an overhaul of Deployers as a contract at the moment.
I believe it only needs to be `internal` right? All of our test files inherit from `Deployers` so they can access the function internally?

**Comment by hensha256** [comment]
Oh I'm sorry this is the wrong repo - Deployers.sol is not in this repo. Going to close your issue, please can you open a new one on the v4-core repo!
