### ISSUE TITLE
[Bug]: Unable to clone clone 'lib/v4-core'

### ISSUE THREAD

**Issue by vincehass** [Uniswap/v4-periphery#78]
### Describe the bug

I followed the step in : https://github.com/uniswapfoundation/v4-template
However I am getting an Error: 
git submodule exited with code 1

Any recommandation how to solve this problem?
Thanks.

### Expected Behavior

I went through all steps for Permission Denied troubleshooting state here:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh

with no luck

### To Reproduce

mkdir testUniswap
 cd testuniswap
 forge init .
 forge install https://github.com/Uniswap/periphery-next

**Comment by 0xV4L3NT1N3** [comment]
Switch to using normal HTTP URL instead of SSH, pending the PR to be merged 

https://github.com/Uniswap/v4-periphery/pull/26
