### ISSUE TITLE
[Bug]: Modify Hooks.Calls into Hooks.Permissions

### ISSUE THREAD

**Issue by LiRiu** [Uniswap/v4-periphery#87]
### Describe the bug

v4-core was updated.
struct Hooks.Calls has been modified into Hooks.Permissions
If not modified, the [BaseHook.sol](https://github.com/Uniswap/v4-periphery/blob/main/contracts/BaseHook.sol) may not be able to compile.

### Expected Behavior

compile complete.

**Comment by hensha256** [comment]
Hi! This is being updated in PR #74 ! That PR should be merged before the end of this week

**Comment by LiRiu** [comment]
Thanks, Looking forward to it very much.
