### ISSUE TITLE
[Bug]: Hook examples should check that the caller is the poolManager and that the sender is the hook itself

### ISSUE THREAD

**Issue by snreynolds** [Uniswap/v4-periphery#88]
### Describe the bug

I think some hook examples like FullRange.sol do not call out to the onlyByManager modifier and also need to check that the original sender is itself.

### Expected Behavior

Add onlyByManager modifier, check sender == address(this)

**Comment by hensha256** [comment]
`sender == address(this)` isnt for hooks necessarily - its for contracts with a `lockAcquired` which shouldnt be all hooks

**Comment by saucepoint** [comment]
Hi! thanks for flagging -- going to close this issue because:

1) hook examples no longer live in the main branch

2) custom accounting will allow for a more v2-style curve with v2 interfaces. reference implementation https://github.com/hensha256/v2-on-v4
