### ISSUE TITLE
[Bug]: BaseHooks.sol need to adapt to the new version v4-core.

### ISSUE THREAD

**Issue by LiRiu** [Uniswap/v4-periphery#90]
### Describe the bug

The IPoolManager.ModifyPositionParams structure is used in BaseHooks, and this structure has been deleted in commit 36160ced8440fe211805f38860334359c73ef490.
This error causes the Hooks Example to fail to compile.

### Expected Behavior

Change all IPoolManager.ModifyPositionParams to ModifyLiquidityParams.

**Comment by saucepoint** [comment]
addressed in https://github.com/Uniswap/v4-periphery/pull/89
