### ISSUE TITLE
current BaseHook implementation makes hooks hard to combine

### ISSUE THREAD

**Issue by ferencdg** [Uniswap/v4-periphery#91]
### Component

Pool Interaction, Hooks

### Describe the suggested feature and problem it solves.

I have two hooks:
HookA, HookB and both of them derives from BaseHook and also initialize BaseHook. Now I want to create ComboHook which derives from HookA and HookB, however solidity complains that BaseHook is initialized twice (through HookA and HookB). 

### Describe the desired implementation.

Maybe make the BaseHook stateless and move out the _poolManager to the actual hook? Or just leave _poolManager in the BaseHook, but don't initialize it in the constructor.

**Comment by ferencdg** [comment]
what I meant is this:
https://github.com/ethereum/solidity/issues/4199

**Comment by saucepoint** [comment]
inheritance in solidity is pretty ugly so the tradeoffs are really tricky and you tend to end up in the same place again.

I see a world of multi-featured hooks, but I'm uncertain if that'll be achieved by inheriting abstract contracts. Inheriting two hook contracts means you'll need to need resolve and override function collisions

I'm under the impression that library-ifying hook logic (LimitOrder, GeomeanOracle) will provide better devex for building multi-featured hooks

**Comment by saucepoint** [comment]
I believe this may work better now that `poolManager` is saved via `ImmutableState`

https://github.com/Uniswap/v4-periphery/commit/a9cfd3878d0acc7bc49ffbb39ea89560740b5454d
